# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for PGAIView Backend
Creates standalone executable with all dependencies
"""

block_cipher = None

a = Analysis(
    ['run_backend.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app_config.yml', '.'),
        ('backend/app', 'backend/app'),
    ],
    hiddenimports=[
        # Uvicorn and all submodules
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.loops.uvloop',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'uvicorn.config',
        'uvicorn.importer',
        'uvicorn.main',
        'uvicorn.middleware',
        'uvicorn.middleware.proxy_headers',
        'uvicorn.server',
        'uvicorn.supervisors',
        'uvicorn.supervisors.statreload',
        'uvicorn.supervisors.multiprocess',
        # ASGI servers
        'h11',
        'httptools',
        'websockets',
        'wsproto',
        'asyncio',
        # Database drivers
        'psycopg2',
        'psycopg2.extras',
        'psycopg2._psycopg',
        'cx_Oracle',
        'oracledb',
        'oracledb.thick_impl',
        'oracledb.thin_impl',
        'mysql.connector',
        'mysql.connector.pooling',
        'mysql.connector.cursor',
        'mysql.connector.connection',
        'sqlite3',
        # FastAPI and dependencies
        'fastapi',
        'fastapi.applications',
        'fastapi.routing',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.middleware.httpsredirect',
        'fastapi.middleware.trustedhost',
        'fastapi.middleware.gzip',
        'fastapi.responses',
        'fastapi.encoders',
        'fastapi.exceptions',
        'fastapi.params',
        'fastapi.security',
        'starlette',
        'starlette.applications',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.responses',
        'starlette.requests',
        'starlette.background',
        'starlette.datastructures',
        'starlette.exceptions',
        # Pydantic
        'pydantic',
        'pydantic.fields',
        'pydantic.main',
        'pydantic.types',
        'pydantic.validators',
        'pydantic.error_wrappers',
        'pydantic_core',
        # YAML
        'yaml',
        'yaml.loader',
        'yaml.dumper',
        'yaml.scanner',
        'yaml.parser',
        # LLM providers
        'openai',
        'openai.types',
        'openai.resources',
        'langchain',
        'langchain.chains',
        'langchain.prompts',
        'langchain.schema',
        'langchain.llms',
        'langchain.chat_models',
        'langchain_openai',
        'langchain_openai.chat_models',
        'langchain_openai.llms',
        'langchain_community',
        'langchain_community.chat_models',
        'langchain_community.llms',
        'langgraph',
        'langgraph.graph',
        'langgraph.graph.graph',
        'langgraph.graph.state',
        'langgraph.prebuilt',
        'langgraph.prebuilt.tool_executor',
        'langgraph.prebuilt.chat_agent_executor',
        'tiktoken',
        'tiktoken.core',
        'tiktoken_ext',
        'tiktoken_ext.openai_public',
        'regex',
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.cookies',
        'requests.models',
        'requests.sessions',
        'urllib3',
        'urllib3.connection',
        'urllib3.connectionpool',
        'urllib3.poolmanager',
        # XML modules
        'xml',
        'xml.dom',
        'xml.dom.minidom',
        'xml.etree',
        'xml.etree.ElementTree',
        # JSON and encoding
        'json',
        'orjson',
        'ujson',
        # Additional utilities
        'typing_extensions',
        'email_validator',
        'python_multipart',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'sniffio',
        'certifi',
        'charset_normalizer',
        'idna',
        'click',
        'colorama',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='databaseai-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
